#!/usr/bin/env bash
set -ex
echo PRUNING MINECRAFT
restic forget --tag minecraft-world \
              --keep-last 15 \
              --keep-within-hourly 1d \
              --keep-within-daily 7d \
              --keep-within-weekly 30d \
              --keep-within-monthly 1y \
              --keep-within-yearly 100y
