apiVersion: v1
kind: Namespace
metadata:
    name: homepage
    labels:
        app.kubernetes.io/name: homepage
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: homepage
    namespace: homepage
    labels:
        app.kubernetes.io/name: homepage
secrets:
    - name: homepage
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
    name: homepage
    namespace: homepage
    labels:
        app.kubernetes.io/name: homepage
    annotations:
        kubernetes.io/service-account.name: homepage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: homepage
    labels:
        app.kubernetes.io/name: homepage
rules:
    - apiGroups: [""]
      resources: ["namespaces", "pods", "nodes"]
      verbs: ["get", "list"]
    - apiGroups: ["extensions", "networking.k8s.io"]
      resources: ["ingresses"]
      verbs: ["get", "list"]
    - apiGroups: ["traefik.io"]
      resources: ["ingressroutes"]
      verbs: ["get", "list"]
    - apiGroups: ["gateway.networking.k8s.io"]
      resources: ["httproutes", "gateways"]
      verbs: ["get", "list"]
    - apiGroups: ["metrics.k8s.io"]
      resources: ["nodes", "pods"]
      verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: homepage
    labels:
        app.kubernetes.io/name: homepage
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: homepage
subjects:
    - kind: ServiceAccount
      name: homepage
      namespace: homepage
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: homepage
    namespace: homepage
    labels:
        app.kubernetes.io/name: homepage
spec:
    replicas: 1
    revisionHistoryLimit: 3
    selector:
        matchLabels:
            app.kubernetes.io/name: homepage
    template:
        metadata:
            labels:
                app.kubernetes.io/name: homepage
        spec:
            serviceAccountName: homepage
            automountServiceAccountToken: true
            containers:
                - name: homepage
                  image: ghcr.io/gethomepage/homepage:v1.8.0
                  ports:
                      - name: http
                        containerPort: 3000
                  env:
                      - name: HOMEPAGE_ALLOWED_HOSTS
                        value: homepage.example.com
                  readinessProbe:
                      httpGet:
                          path: /
                          port: http
                      initialDelaySeconds: 5
                      periodSeconds: 10
                  livenessProbe:
                      httpGet:
                          path: /
                          port: http
                      initialDelaySeconds: 15
                      periodSeconds: 20
                  resources:
                      requests:
                          cpu: 50m
                          memory: 64Mi
                      limits:
                          memory: 256Mi
                  volumeMounts:
                      - name: homepage-config
                        mountPath: /app/config/settings.yaml
                        subPath: settings.yaml
                        readOnly: true
                      - name: homepage-config
                        mountPath: /app/config/services.yaml
                        subPath: services.yaml
                        readOnly: true
                      - name: homepage-config
                        mountPath: /app/config/bookmarks.yaml
                        subPath: bookmarks.yaml
                        readOnly: true
                      - name: homepage-config
                        mountPath: /app/config/widgets.yaml
                        subPath: widgets.yaml
                        readOnly: true
                      - name: homepage-config
                        mountPath: /app/config/kubernetes.yaml
                        subPath: kubernetes.yaml
                        readOnly: true
                      - name: homepage-config
                        mountPath: /app/config/docker.yaml
                        subPath: docker.yaml
                        readOnly: true
                      - name: homepage-config
                        mountPath: /app/config/custom.css
                        subPath: custom.css
                        readOnly: true
                      - name: homepage-config
                        mountPath: /app/config/custom.js
                        subPath: custom.js
                        readOnly: true
                      - name: logs
                        mountPath: /app/config/logs
            volumes:
                - name: homepage-config
                  configMap:
                      name: homepage
                - name: logs
                  emptyDir: {}
