import { LinuxUser, type LinuxOwnership } from "@k8ts/instruments"
export const userMumble = LinuxUser(2100, "mumble").sameGroup()
export const userFactorio = LinuxUser(845, "factorio").sameGroup()
export const userSyncthing = LinuxUser(2101, "syncthing").sameGroup()
export const userWikiJs = LinuxUser(2102, "wikijs").sameGroup()
export const userTheLounge = LinuxUser(2103, "thelounge").sameGroup()
export const userMedia = LinuxUser(2104, "media").sameGroup()
export const userScrutiny = LinuxUser(2105, "scrutiny").sameGroup()
export const userGlances = LinuxUser(2106, "glances").sameGroup()
export const userSyncthingDiscovery = LinuxUser(2107, "syncthing-discovery").sameGroup()
export const userMinecraft = LinuxUser(2109, "minecraft").sameGroup()
export const userMinecraftPack = LinuxUser(2110, "minecraft-pack").sameGroup()
export const userGrb = LinuxUser(2111, "grb").sameGroup()
export const userSpeedtestTracker = LinuxUser(2112, "speedtest-tracker").sameGroup()
export const userHomepage = LinuxUser(2113, "homepage").sameGroup()
export const userWgPortal: LinuxOwnership = LinuxUser(2114, "wg-portal").sameGroup()
