import { LinuxUser, type LinuxOwnership } from "@k8ts/instruments"
export const userMumble = new LinuxUser(2100, "mumble").sameGroup()
export const userFactorio = new LinuxUser(845, "factorio").sameGroup()
export const userSyncthing = new LinuxUser(2101, "syncthing").sameGroup()
export const userWikiJs = new LinuxUser(2102, "wikijs").sameGroup()
export const userTheLounge = new LinuxUser(2103, "thelounge").sameGroup()
export const userMedia = new LinuxUser(2104, "media").sameGroup()
export const userScrutiny = new LinuxUser(2105, "scrutiny").sameGroup()
export const userGlances = new LinuxUser(2106, "glances").sameGroup()
export const userSyncthingDiscovery = new LinuxUser(2107, "syncthing-discovery").sameGroup()
export const userMinecraft = new LinuxUser(2109, "minecraft").sameGroup()
export const userMinecraftPack = new LinuxUser(2110, "minecraft-pack").sameGroup()
export const userGrb = new LinuxUser(2111, "grb").sameGroup()
export const userSpeedtestTracker = new LinuxUser(2112, "speedtest-tracker").sameGroup()
export const userHomepage = new LinuxUser(2113, "homepage").sameGroup()
export const userWgPortal: LinuxOwnership = new LinuxUser(2114, "wg-portal").sameGroup()
